version: '3'

# run maven install before building images

services:
  # Employee Microservice
  lecture-planner-employee-db:
    image: mariadb
    # no external access needed
#    ports:
#      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db_example
      - MYSQL_ROOT_PASSWORD=mypass
  lecture-planner-employee:
    image: alexx882/lecture-planner-employee
    build: lecture-planner-employee-service
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=lecture-planner-employee-db
      - MYSQL_PORT=3306
    depends_on:
      - lecture-planner-employee-db
    restart: on-failure # db might not be ready yet -> restart until it is

  # Lecture Microservice
  lecture-planner-lecture-db:
    image: mariadb
    # no external access needed
#    ports:
#      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db_example
      - MYSQL_ROOT_PASSWORD=mypass
  lecture-planner-lecture:
    image: alexx882/lecture-planner-lecture
    build: lecture-planner-lecture-service
    ports:
      - "8082:8082"
    environment:
      - MYSQL_HOST=lecture-planner-lecture-db
      - MYSQL_PORT=3306
    depends_on:
      - lecture-planner-lecture-db
    restart: on-failure # db might not be ready yet -> restart until it is

  # GraphQL Microservice
  lecture-planner-graphql:
    image: alexx882/lecture-planner-graphql
    build: lecture-planner-graphql
    ports:
      - "8083:8083"
    environment:
      - EMPLOYEE_HOST=lecture-planner-employee
      - EMPLOYEE_PORT=8081
      - LECTURE_HOST=lecture-planner-lecture
      - LECTURE_PORT=8082
    depends_on:
      - lecture-planner-lecture
      - lecture-planner-employee
    restart: on-failure

  # Frontend Microservice
  lecture-planner-frontend:
    image: alexx882/lecture-planner-frontend
    build: lecture-planner-frontend
    ports:
      - "8080:8080"
    environment:
      - GRAPHQL_HOST=lecture-planner-graphql
      - GRAPHQL_PORT=8083
    depends_on:
      - lecture-planner-graphql
    restart: on-failure
