apiVersion: v1
kind: Service
metadata:
  name: lecture-planner-lecture
spec:
  type: LoadBalancer
  selector:
    app: lecture-planner-lecture
  ports:
    - name: http
      targetPort: 8082
      port: 80
      nodePort: 30002
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecture-planner-lecture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lecture-planner-lecture
  template:
    metadata:
      labels:
        app: lecture-planner-lecture
    spec:
      containers:
        - name: lecture-planner-lecture
          image: alexx882/lecture-planner-lecture
          env:
            - name: MYSQL_HOST
              value: lecture-planner-lecture-db
            - name: MYSQL_PORT
              value: '3306'
          ports:
            - containerPort: 8082
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: lecture-planner-lecture-db
spec:
  type: LoadBalancer
  selector:
    app: lecture-planner-lecture-db
  ports:
    - name: mariadb
      port: 3306
      targetPort: 3306
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecture-planner-lecture-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lecture-planner-lecture-db
  template:
    metadata:
      labels:
        app: lecture-planner-lecture-db
    spec:
      containers:
        - name: lecture-planner-lecture-db
          image: mariadb
          env:
            - name: MYSQL_DATABASE
              value: db_example
            - name: MYSQL_ROOT_PASSWORD
              value: mypass
          ports:
            - containerPort: 3306
          imagePullPolicy: IfNotPresent